[profile.default]
solc_version = "0.8.26"
evm_version = "shanghai"
auto_detect_solc = false
auto_detect_remappings = false
deny_warnings = true
optimizer = true
optimizer_runs = 400
src = 'src'
out = 'out'
libs = ["dependencies"]
remappings = [
    "/=src/",
    "forge-std/=dependencies/forge-std-1.9.2/src/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
    "@solmate/=dependencies/solmate-1.0.0/src/"
]

[soldeer]
remappings_generate = false
remappings_regenerate = false
remappings_version = false
remappings_prefix = ""
recursive_deps = false

[dependencies]
forge-std = { version = "1.9.2", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_2_06-08-2024_17:31:25_forge-std-1.9.2.zip" }
"solmate" = { version = "1.0.0", git = "https://github.com/transmissions11/solmate.git", rev = "0384dbaaa4fcb5715738a9254a7c0a4cb62cf458" }
"@openzeppelin-contracts" = "5.0.2"
